name: ci-golang-workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.20', '1.21', '1.22']

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

        with:
          go-version: ${{ matrix.version }}

      - name: Execute tests
        run: go test

      - name: Install dependencies
        run: go run math.go